// <auto-generated />
using System;
using FishingStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishingStore.Data.Migrations
{
    [DbContext(typeof(FishingStoreContext))]
    [Migration("20241102094158_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishingStore.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FishingStore.Data.Models.FullSet", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HookGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LineGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ReelGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RodGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("HookGuid");

                    b.HasIndex("LineGuid");

                    b.HasIndex("ReelGuid");

                    b.HasIndex("RodGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("FullSets");
                });

            modelBuilder.Entity("FishingStore.Data.Models.Hook", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Hooks");
                });

            modelBuilder.Entity("FishingStore.Data.Models.Line", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LineType")
                        .HasColumnType("int");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Guid");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("FishingStore.Data.Models.Reel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReelSize")
                        .HasColumnType("int");

                    b.Property<int>("SpoolCapacity")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Reels");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("d75b1108-5cdf-469c-bb52-8cb743a6f255"),
                            Brand = "Penn",
                            Description = "Lightweight design that doesn’t compromise on strength.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 102.07m,
                            ReelSize = 4000,
                            SpoolCapacity = 450
                        },
                        new
                        {
                            Guid = new Guid("12991ff7-0a19-4900-af20-bbecb7b19297"),
                            Brand = "Daiwa",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 113.20m,
                            ReelSize = 3000,
                            SpoolCapacity = 530
                        },
                        new
                        {
                            Guid = new Guid("beec55a4-2239-4dd5-a5f4-66dc63be4df4"),
                            Brand = "Shimano",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 100.48m,
                            ReelSize = 3500,
                            SpoolCapacity = 310
                        },
                        new
                        {
                            Guid = new Guid("27fc943b-0a44-42a5-a3ca-c8e1a58b70ff"),
                            Brand = "Abu Garcia",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 379.30m,
                            ReelSize = 6000,
                            SpoolCapacity = 710
                        },
                        new
                        {
                            Guid = new Guid("efe50ae4-79e6-4ee0-8f8f-a278dfb84664"),
                            Brand = "Penn",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 200.37m,
                            ReelSize = 3500,
                            SpoolCapacity = 670
                        },
                        new
                        {
                            Guid = new Guid("00535581-0f04-4917-a635-1084d5471546"),
                            Brand = "Quantum",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 67.59m,
                            ReelSize = 5500,
                            SpoolCapacity = 730
                        },
                        new
                        {
                            Guid = new Guid("9f8e5f85-4af3-48ec-ba5b-09bcefc06e80"),
                            Brand = "Shimano",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 217.74m,
                            ReelSize = 4500,
                            SpoolCapacity = 700
                        },
                        new
                        {
                            Guid = new Guid("3f610f32-5a9c-489d-8e92-e8b25c28ab02"),
                            Brand = "Lew's",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 635.09m,
                            ReelSize = 5000,
                            SpoolCapacity = 530
                        },
                        new
                        {
                            Guid = new Guid("144ac8d1-146c-4f07-a9ed-a3eb803622fa"),
                            Brand = "Abu Garcia",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 525.36m,
                            ReelSize = 2000,
                            SpoolCapacity = 480
                        },
                        new
                        {
                            Guid = new Guid("2e4fa9f6-b9cf-4d27-a684-089f36fd8f7e"),
                            Brand = "Shimano",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 95.25m,
                            ReelSize = 5500,
                            SpoolCapacity = 500
                        },
                        new
                        {
                            Guid = new Guid("0e48681f-3a7d-457e-94d5-c9fffd34fe90"),
                            Brand = "Okuma",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 256.86m,
                            ReelSize = 5500,
                            SpoolCapacity = 410
                        },
                        new
                        {
                            Guid = new Guid("65ead2f5-d241-4295-80fa-850e43beb89e"),
                            Brand = "Okuma",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 609.99m,
                            ReelSize = 4500,
                            SpoolCapacity = 320
                        },
                        new
                        {
                            Guid = new Guid("bf05f00a-e517-4929-bcea-ef478020e731"),
                            Brand = "Daiwa",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 122.89m,
                            ReelSize = 3500,
                            SpoolCapacity = 320
                        },
                        new
                        {
                            Guid = new Guid("419369f8-aa29-49ea-bc85-21c364d3b935"),
                            Brand = "Penn",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 583.41m,
                            ReelSize = 6000,
                            SpoolCapacity = 400
                        },
                        new
                        {
                            Guid = new Guid("49310f02-7817-411a-a7a3-1a25c03270da"),
                            Brand = "Abu Garcia",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 641.87m,
                            ReelSize = 4500,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("1db3c112-bb10-4ee9-85ef-fefce71af6e2"),
                            Brand = "Daiwa",
                            Description = "High-performance reel with exceptional durability and smooth drag.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 595.33m,
                            ReelSize = 4000,
                            SpoolCapacity = 570
                        },
                        new
                        {
                            Guid = new Guid("86eeec0b-d170-4aec-8b0d-d0cb84dc2a98"),
                            Brand = "Quantum",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 300.72m,
                            ReelSize = 5500,
                            SpoolCapacity = 240
                        },
                        new
                        {
                            Guid = new Guid("db7f4e0f-95d4-4d45-aa89-71a62aab92f9"),
                            Brand = "Daiwa",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 486.31m,
                            ReelSize = 2000,
                            SpoolCapacity = 270
                        },
                        new
                        {
                            Guid = new Guid("396a122c-1503-45ee-a5a4-9a18d17c3b30"),
                            Brand = "Daiwa",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 480.06m,
                            ReelSize = 5000,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("29eee38e-d874-43b5-98c4-3fd7ab30442f"),
                            Brand = "Daiwa",
                            Description = "Lightweight design that doesn’t compromise on strength.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 149.28m,
                            ReelSize = 1000,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("b802ee04-af68-4eb3-a4f4-bfce11736090"),
                            Brand = "Okuma",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 658.80m,
                            ReelSize = 2000,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("ba72169d-92f8-4af6-9960-5d565572978f"),
                            Brand = "Okuma",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 296.38m,
                            ReelSize = 5000,
                            SpoolCapacity = 570
                        },
                        new
                        {
                            Guid = new Guid("584b2601-e039-48b7-b4e1-0ef09aaa8691"),
                            Brand = "Okuma",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 610.08m,
                            ReelSize = 1000,
                            SpoolCapacity = 540
                        },
                        new
                        {
                            Guid = new Guid("dd664aa7-4d07-452b-83ff-49dbd8ffb3e8"),
                            Brand = "Okuma",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 689.32m,
                            ReelSize = 2000,
                            SpoolCapacity = 600
                        },
                        new
                        {
                            Guid = new Guid("afc286a9-7a6e-4b47-b04c-8406dcc1cddb"),
                            Brand = "Shimano",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 469.32m,
                            ReelSize = 1000,
                            SpoolCapacity = 250
                        },
                        new
                        {
                            Guid = new Guid("21acdac9-aca0-455c-a505-a155e18b8488"),
                            Brand = "Abu Garcia",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 111.13m,
                            ReelSize = 5000,
                            SpoolCapacity = 630
                        },
                        new
                        {
                            Guid = new Guid("76a638d2-0870-4bcc-b8da-779dcfc8d79a"),
                            Brand = "Quantum",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 255.86m,
                            ReelSize = 2000,
                            SpoolCapacity = 710
                        },
                        new
                        {
                            Guid = new Guid("3f0485a7-6bc8-48d7-b887-d5a4059cfbfc"),
                            Brand = "Abu Garcia",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 583.96m,
                            ReelSize = 4500,
                            SpoolCapacity = 410
                        },
                        new
                        {
                            Guid = new Guid("f38635a3-5f22-4d52-b411-657e3b3823d0"),
                            Brand = "Okuma",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 487.82m,
                            ReelSize = 1000,
                            SpoolCapacity = 700
                        },
                        new
                        {
                            Guid = new Guid("53c02dcd-0fdb-4e4e-a24f-6dcefde5abe5"),
                            Brand = "Abu Garcia",
                            Description = "Lightweight design that doesn’t compromise on strength.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 636.94m,
                            ReelSize = 5000,
                            SpoolCapacity = 240
                        },
                        new
                        {
                            Guid = new Guid("d2227fc5-1dcc-414f-a5b2-9cfd25e4a342"),
                            Brand = "Shimano",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 130.09m,
                            ReelSize = 2000,
                            SpoolCapacity = 640
                        },
                        new
                        {
                            Guid = new Guid("0a93751d-a31c-4004-94d8-38795d5b477c"),
                            Brand = "Daiwa",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 438.53m,
                            ReelSize = 5500,
                            SpoolCapacity = 540
                        },
                        new
                        {
                            Guid = new Guid("4b743324-dda2-4967-9582-bb59b773def3"),
                            Brand = "Penn",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 219.84m,
                            ReelSize = 2000,
                            SpoolCapacity = 200
                        },
                        new
                        {
                            Guid = new Guid("100fdbbc-a90f-40fa-bf36-9951a18e30c1"),
                            Brand = "Okuma",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tatula SV 2500",
                            Price = 227.67m,
                            ReelSize = 5500,
                            SpoolCapacity = 620
                        },
                        new
                        {
                            Guid = new Guid("e1ba8772-c489-49e3-820a-ed059110b6f6"),
                            Brand = "Shimano",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 253.36m,
                            ReelSize = 4000,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("171afe3a-9574-47db-adb1-2205fc25b38c"),
                            Brand = "Okuma",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 188.36m,
                            ReelSize = 5000,
                            SpoolCapacity = 310
                        },
                        new
                        {
                            Guid = new Guid("f057e7eb-176d-48b6-9c4f-6b507758b4ba"),
                            Brand = "Okuma",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 141.88m,
                            ReelSize = 6000,
                            SpoolCapacity = 350
                        },
                        new
                        {
                            Guid = new Guid("903f7c96-e274-4131-b920-d0ad9e281095"),
                            Brand = "Quantum",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 122.50m,
                            ReelSize = 3500,
                            SpoolCapacity = 790
                        },
                        new
                        {
                            Guid = new Guid("5fd0ef8b-d639-46ee-b1d6-461f61a4f57b"),
                            Brand = "Abu Garcia",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 503.06m,
                            ReelSize = 5500,
                            SpoolCapacity = 290
                        },
                        new
                        {
                            Guid = new Guid("ae3f0c9f-e0e7-4401-a8d0-7c1acaea9bbf"),
                            Brand = "Penn",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 312.57m,
                            ReelSize = 2000,
                            SpoolCapacity = 470
                        },
                        new
                        {
                            Guid = new Guid("91f6ce37-d0cc-48ad-8e51-d2689abe4e94"),
                            Brand = "Abu Garcia",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 570.38m,
                            ReelSize = 5000,
                            SpoolCapacity = 490
                        },
                        new
                        {
                            Guid = new Guid("e695433e-9cf4-4bed-b0d0-af2414e2e873"),
                            Brand = "Abu Garcia",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 145.39m,
                            ReelSize = 5500,
                            SpoolCapacity = 680
                        },
                        new
                        {
                            Guid = new Guid("8dc39ff6-7021-49c0-95a6-e24bc50fa71a"),
                            Brand = "Okuma",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 513.04m,
                            ReelSize = 5000,
                            SpoolCapacity = 540
                        },
                        new
                        {
                            Guid = new Guid("ac8c0269-3ab8-4d0f-a8ff-c7c700a1f06a"),
                            Brand = "Daiwa",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 658.45m,
                            ReelSize = 5500,
                            SpoolCapacity = 220
                        },
                        new
                        {
                            Guid = new Guid("b7091b5f-3b6a-468e-9af4-20a18444768a"),
                            Brand = "Penn",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 486.18m,
                            ReelSize = 1000,
                            SpoolCapacity = 600
                        },
                        new
                        {
                            Guid = new Guid("4f954d81-ae7d-49f8-8fc3-074d2b148a34"),
                            Brand = "Abu Garcia",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 600.36m,
                            ReelSize = 5000,
                            SpoolCapacity = 280
                        },
                        new
                        {
                            Guid = new Guid("6fc09cc5-d33d-46f2-b6b5-732cb6cffcfa"),
                            Brand = "Penn",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 157.89m,
                            ReelSize = 1000,
                            SpoolCapacity = 280
                        },
                        new
                        {
                            Guid = new Guid("70da30f5-996c-4d5c-a4b7-72e2f149d2fb"),
                            Brand = "Lew's",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 224.66m,
                            ReelSize = 4000,
                            SpoolCapacity = 640
                        },
                        new
                        {
                            Guid = new Guid("93350079-182d-474b-8469-785f5256f5a2"),
                            Brand = "Okuma",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 113.03m,
                            ReelSize = 4500,
                            SpoolCapacity = 350
                        },
                        new
                        {
                            Guid = new Guid("8632b692-01d5-4514-b9c8-05893b196193"),
                            Brand = "Shimano",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 168.79m,
                            ReelSize = 1000,
                            SpoolCapacity = 580
                        });
                });

            modelBuilder.Entity("FishingStore.Data.Models.Rod", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Guid");

                    b.ToTable("Rods");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("dedc1bf5-6349-4e7c-930f-8ecb29cfce33"),
                            Action = 170,
                            Brand = "Shimano",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Catana",
                            Price = 782.49m
                        },
                        new
                        {
                            Guid = new Guid("3f2efd66-3ba2-4565-a1f9-028d6e47d04c"),
                            Action = 120,
                            Brand = "Abu Garcia",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Procyon",
                            Price = 774.05m
                        },
                        new
                        {
                            Guid = new Guid("0439e750-ac0c-46b6-bc22-7eea168866fb"),
                            Action = 150,
                            Brand = "Daiwa",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Phantom",
                            Price = 492.85m
                        },
                        new
                        {
                            Guid = new Guid("624d964f-0e91-47e9-8019-670ed23cc5c1"),
                            Action = 140,
                            Brand = "Penn",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Stradic CI4+",
                            Price = 502.59m
                        },
                        new
                        {
                            Guid = new Guid("57e3147b-800f-4d20-8de5-f948763bbab6"),
                            Action = 150,
                            Brand = "Shimano",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Phantom",
                            Price = 245.57m
                        },
                        new
                        {
                            Guid = new Guid("883ebe23-22a6-49da-9d4b-cefe0e465018"),
                            Action = 110,
                            Brand = "Abu Garcia",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Phantom",
                            Price = 672.24m
                        },
                        new
                        {
                            Guid = new Guid("8c68bac8-14d3-4be5-9f3c-f009c80c7ee2"),
                            Action = 40,
                            Brand = "Abu Garcia",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Celilo",
                            Price = 846.54m
                        },
                        new
                        {
                            Guid = new Guid("025f3170-4bba-40e8-82fc-6407092357f7"),
                            Action = 90,
                            Brand = "Shimano",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Revo SX",
                            Price = 480.72m
                        },
                        new
                        {
                            Guid = new Guid("c445e4a2-8005-4dfc-8d50-b317b287a0a4"),
                            Action = 60,
                            Brand = "Okuma",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 360,
                            Model = "Celilo",
                            Price = 120.03m
                        },
                        new
                        {
                            Guid = new Guid("842c8f97-fc25-429a-9a2e-76f1d3bc5558"),
                            Action = 150,
                            Brand = "Daiwa",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Celilo",
                            Price = 617.94m
                        },
                        new
                        {
                            Guid = new Guid("e0402c03-a9ae-4bd9-99f0-0b836458fa15"),
                            Action = 60,
                            Brand = "Abu Garcia",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Veritas",
                            Price = 674.85m
                        },
                        new
                        {
                            Guid = new Guid("72922bad-f1ad-43f0-8bd5-ee95fbb29273"),
                            Action = 130,
                            Brand = "Shimano",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Tatula LT",
                            Price = 898.62m
                        },
                        new
                        {
                            Guid = new Guid("d098eafe-b7b3-4409-9fbc-4eee0b8c0c01"),
                            Action = 130,
                            Brand = "Abu Garcia",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Phantom",
                            Price = 675.10m
                        },
                        new
                        {
                            Guid = new Guid("5bbec1c4-657b-40cf-a7ff-6613bbccf5ab"),
                            Action = 10,
                            Brand = "Abu Garcia",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Revo SX",
                            Price = 443.17m
                        },
                        new
                        {
                            Guid = new Guid("644da45d-0242-407a-aa24-58bff2050857"),
                            Action = 140,
                            Brand = "Okuma",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Battle II",
                            Price = 808.81m
                        },
                        new
                        {
                            Guid = new Guid("4743f203-8b74-43f2-a299-e271e16f1cc2"),
                            Action = 70,
                            Brand = "Penn",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Tsunami",
                            Price = 100.51m
                        },
                        new
                        {
                            Guid = new Guid("2f3b3c03-697c-4a47-8837-9835a08fba43"),
                            Action = 50,
                            Brand = "Penn",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 360,
                            Model = "Tsunami",
                            Price = 529.36m
                        },
                        new
                        {
                            Guid = new Guid("7d4bbeca-c7c3-423c-87f2-ed0e44f4d6a7"),
                            Action = 40,
                            Brand = "Shimano",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Stradic CI4+",
                            Price = 338.89m
                        },
                        new
                        {
                            Guid = new Guid("599db364-4c8c-4034-82c2-5fc3d0902ca6"),
                            Action = 150,
                            Brand = "Abu Garcia",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Revo SX",
                            Price = 795.63m
                        },
                        new
                        {
                            Guid = new Guid("3a160f4b-06de-42c6-8f9a-29e0dd70ee11"),
                            Action = 90,
                            Brand = "Penn",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Procyon",
                            Price = 320.80m
                        },
                        new
                        {
                            Guid = new Guid("a294ebc4-aee8-4159-b413-f94d203de37a"),
                            Action = 130,
                            Brand = "Daiwa",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Tatula LT",
                            Price = 590.16m
                        },
                        new
                        {
                            Guid = new Guid("20cc0c2c-6b0b-4e57-b791-b40237fe7a24"),
                            Action = 160,
                            Brand = "Penn",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Veritas",
                            Price = 714.90m
                        },
                        new
                        {
                            Guid = new Guid("0945eab6-9d6a-4777-aee5-fb7c1f51ae4f"),
                            Action = 20,
                            Brand = "Abu Garcia",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Stradic CI4+",
                            Price = 382.94m
                        },
                        new
                        {
                            Guid = new Guid("e24003db-04a2-4935-aa57-5a1082030c7a"),
                            Action = 110,
                            Brand = "Okuma",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Tatula LT",
                            Price = 142.90m
                        },
                        new
                        {
                            Guid = new Guid("db54cf5a-29ee-4496-9a97-793dfb80e52d"),
                            Action = 50,
                            Brand = "Shimano",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 360,
                            Model = "Phantom",
                            Price = 614.11m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FishingStore.Data.Models.FullSet", b =>
                {
                    b.HasOne("FishingStore.Data.Models.Hook", "Hook")
                        .WithMany()
                        .HasForeignKey("HookGuid");

                    b.HasOne("FishingStore.Data.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineGuid");

                    b.HasOne("FishingStore.Data.Models.Reel", "Reel")
                        .WithMany()
                        .HasForeignKey("ReelGuid");

                    b.HasOne("FishingStore.Data.Models.Rod", "Rod")
                        .WithMany()
                        .HasForeignKey("RodGuid");

                    b.HasOne("FishingStore.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("FullSets")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Hook");

                    b.Navigation("Line");

                    b.Navigation("Reel");

                    b.Navigation("Rod");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FishingStore.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("FullSets");
                });
#pragma warning restore 612, 618
        }
    }
}
