// <auto-generated />
using System;
using FishingStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishingStore.Data.Migrations
{
    [DbContext(typeof(FishingStoreContext))]
    [Migration("20241102100500_SeedLines")]
    partial class SeedLines
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FishingStore.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FishingStore.Data.Models.FullSet", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HookGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LineGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ReelGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RodGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Guid");

                    b.HasIndex("HookGuid");

                    b.HasIndex("LineGuid");

                    b.HasIndex("ReelGuid");

                    b.HasIndex("RodGuid");

                    b.HasIndex("UserGuid");

                    b.ToTable("FullSets");
                });

            modelBuilder.Entity("FishingStore.Data.Models.Hook", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Hooks");
                });

            modelBuilder.Entity("FishingStore.Data.Models.Line", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Diameter")
                        .HasColumnType("float");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LineType")
                        .HasColumnType("int");

                    b.Property<double>("MaxWeight")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Guid");

                    b.ToTable("Lines");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("f710a4e9-64a1-49f2-8a85-e1e14c180b6e"),
                            Brand = "SpiderWire",
                            Description = "Designed for maximum sensitivity and low visibility.",
                            Diameter = 0.75,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 16.32,
                            Model = "CXX Premium",
                            Price = 22.10m
                        },
                        new
                        {
                            Guid = new Guid("a09f80e1-a337-423b-b24b-b4535bc6a459"),
                            Brand = "Sufix",
                            Description = "Resistant to abrasions and knots, ensuring durability.",
                            Diameter = 0.32000000000000001,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 16.32,
                            Model = "Braid X8",
                            Price = 45.94m
                        },
                        new
                        {
                            Guid = new Guid("5828c0aa-a277-4d2f-9686-4ac889b652b5"),
                            Brand = "Berkley",
                            Description = "Ideal for both freshwater and saltwater fishing.",
                            Diameter = 0.81999999999999995,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 7.7199999999999998,
                            Model = "Tensile Line",
                            Price = 11.56m
                        },
                        new
                        {
                            Guid = new Guid("4775574b-6699-432f-981b-183ae005d7f0"),
                            Brand = "Yo-Zuri",
                            Description = "Strong and reliable for various fishing conditions.",
                            Diameter = 0.58999999999999997,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 16.289999999999999,
                            Model = "Braid X8",
                            Price = 51.96m
                        },
                        new
                        {
                            Guid = new Guid("b9d75d26-79b0-4bdf-a5fc-491e149d8c2d"),
                            Brand = "SpiderWire",
                            Description = "Enhanced toughness for heavy cover and big fish.",
                            Diameter = 0.54000000000000004,
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 10.41,
                            Model = "Ultra 8",
                            Price = 33.35m
                        },
                        new
                        {
                            Guid = new Guid("2c71e352-3a9e-4d5c-805f-71fa7ae075a4"),
                            Brand = "SpiderWire",
                            Description = "Offers exceptional strength-to-diameter ratio.",
                            Diameter = 0.94999999999999996,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 14.279999999999999,
                            Model = "Stealth Braid",
                            Price = 42.90m
                        },
                        new
                        {
                            Guid = new Guid("58747333-ad70-4b53-ac68-4e742daabff0"),
                            Brand = "SpiderWire",
                            Description = "Advanced technology for better performance in the water.",
                            Diameter = 0.54000000000000004,
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 4.6200000000000001,
                            Model = "InvizX",
                            Price = 11.92m
                        },
                        new
                        {
                            Guid = new Guid("2fc92693-d856-4ba7-ba2e-f6b939fb0503"),
                            Brand = "Sufix",
                            Description = "Resistant to abrasions and knots, ensuring durability.",
                            Diameter = 0.35999999999999999,
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 18.960000000000001,
                            Model = "Braid X8",
                            Price = 33.05m
                        },
                        new
                        {
                            Guid = new Guid("fbfdaf93-24df-4630-b351-ef90c469a387"),
                            Brand = "Yo-Zuri",
                            Description = "Ideal for both freshwater and saltwater fishing.",
                            Diameter = 0.77000000000000002,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 18.489999999999998,
                            Model = "InvizX",
                            Price = 44.72m
                        },
                        new
                        {
                            Guid = new Guid("634d330e-8156-48e6-9740-432f4649e804"),
                            Brand = "P-Line",
                            Description = "Provides superior knot strength and stability.",
                            Diameter = 0.33000000000000002,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 9.3399999999999999,
                            Model = "InvizX",
                            Price = 42.03m
                        },
                        new
                        {
                            Guid = new Guid("a00b1f3b-b206-42ab-adb3-208f072a0796"),
                            Brand = "SpiderWire",
                            Description = "Offers exceptional strength-to-diameter ratio.",
                            Diameter = 0.93999999999999995,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 4.5199999999999996,
                            Model = "Braid X8",
                            Price = 58.21m
                        },
                        new
                        {
                            Guid = new Guid("ab2cf1ac-cbb8-40b2-90d1-2bb14f456951"),
                            Brand = "Seaguar",
                            Description = "Enhanced toughness for heavy cover and big fish.",
                            Diameter = 0.69999999999999996,
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 11.74,
                            Model = "InvizX",
                            Price = 31.59m
                        },
                        new
                        {
                            Guid = new Guid("65cf8ad8-a9e9-4bec-a4e9-c51129a1ac35"),
                            Brand = "Berkley",
                            Description = "Designed for maximum sensitivity and low visibility.",
                            Diameter = 0.87,
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 11.01,
                            Model = "CXX Premium",
                            Price = 48.70m
                        },
                        new
                        {
                            Guid = new Guid("7ed01fba-b6da-493e-89b3-fe2fdb18358b"),
                            Brand = "Sufix",
                            Description = "Strong and reliable for various fishing conditions.",
                            Diameter = 0.83999999999999997,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 4.1699999999999999,
                            Model = "Trilene XL",
                            Price = 30.72m
                        },
                        new
                        {
                            Guid = new Guid("f49218bb-a5fd-47ad-a703-8a883724bf90"),
                            Brand = "Berkley",
                            Description = "Ideal for both freshwater and saltwater fishing.",
                            Diameter = 0.26000000000000001,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 18.07,
                            Model = "Tensile Line",
                            Price = 26.53m
                        },
                        new
                        {
                            Guid = new Guid("67e51bc4-d579-469e-a846-d85267096a3f"),
                            Brand = "Seaguar",
                            Description = "Enhanced toughness for heavy cover and big fish.",
                            Diameter = 0.5,
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 9.2599999999999998,
                            Model = "Advanced Fluorocarbon",
                            Price = 30.52m
                        },
                        new
                        {
                            Guid = new Guid("6765e283-6e5b-47b7-9d89-b6b00d2317c6"),
                            Brand = "P-Line",
                            Description = "Advanced technology for better performance in the water.",
                            Diameter = 0.56000000000000005,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 16.719999999999999,
                            Model = "Stealth Braid",
                            Price = 50.46m
                        },
                        new
                        {
                            Guid = new Guid("04d6678c-eea7-4fbd-8cce-4738b95fa6a1"),
                            Brand = "Sufix",
                            Description = "Enhanced toughness for heavy cover and big fish.",
                            Diameter = 0.78000000000000003,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 12.789999999999999,
                            Model = "Stealth Braid",
                            Price = 42.12m
                        },
                        new
                        {
                            Guid = new Guid("ac92109e-e918-46c7-80d0-e540fce22a9d"),
                            Brand = "Berkley",
                            Description = "Lightweight and easy to handle for beginners.",
                            Diameter = 0.13,
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 12.539999999999999,
                            Model = "Super Slick",
                            Price = 56.42m
                        },
                        new
                        {
                            Guid = new Guid("ca35014f-2996-4cda-a406-78165e9dea28"),
                            Brand = "Sufix",
                            Description = "Lightweight and easy to handle for beginners.",
                            Diameter = 0.98999999999999999,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 13.6,
                            Model = "Stealth Braid",
                            Price = 11.76m
                        },
                        new
                        {
                            Guid = new Guid("d6035068-3ef2-4028-8727-21ebab583d14"),
                            Brand = "Yo-Zuri",
                            Description = "Resistant to abrasions and knots, ensuring durability.",
                            Diameter = 0.38,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 6.3300000000000001,
                            Model = "Stealth Braid",
                            Price = 38.06m
                        },
                        new
                        {
                            Guid = new Guid("65853075-103d-427c-8d87-1410cbec5a65"),
                            Brand = "SpiderWire",
                            Description = "Advanced technology for better performance in the water.",
                            Diameter = 0.26000000000000001,
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 11.210000000000001,
                            Model = "InvizX",
                            Price = 32.54m
                        },
                        new
                        {
                            Guid = new Guid("147dee65-6aab-4d53-9682-4a08f5bab8cd"),
                            Brand = "Sufix",
                            Description = "Provides superior knot strength and stability.",
                            Diameter = 0.47999999999999998,
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 2.8199999999999998,
                            Model = "Advanced Fluorocarbon",
                            Price = 23.68m
                        },
                        new
                        {
                            Guid = new Guid("fbf89bed-fa33-464e-8f66-1267f8a23cb6"),
                            Brand = "Sufix",
                            Description = "Strong and reliable for various fishing conditions.",
                            Diameter = 0.93999999999999995,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 19.870000000000001,
                            Model = "CXX Premium",
                            Price = 55.74m
                        },
                        new
                        {
                            Guid = new Guid("387215a5-3914-4273-ae8c-5f66ac5e0c4c"),
                            Brand = "Sufix",
                            Description = "Advanced technology for better performance in the water.",
                            Diameter = 0.81999999999999995,
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 11.640000000000001,
                            Model = "Ultra 8",
                            Price = 47.12m
                        },
                        new
                        {
                            Guid = new Guid("5fdaa89d-373e-4bdf-9b76-43b9cc4d919c"),
                            Brand = "P-Line",
                            Description = "Strong and reliable for various fishing conditions.",
                            Diameter = 1.0,
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 19.23,
                            Model = "Super Slick",
                            Price = 30.08m
                        },
                        new
                        {
                            Guid = new Guid("e4a9966b-124e-4583-a2c5-ad57ae71b009"),
                            Brand = "Sufix",
                            Description = "Enhanced toughness for heavy cover and big fish.",
                            Diameter = 0.19,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 19.129999999999999,
                            Model = "Super Slick",
                            Price = 21.67m
                        },
                        new
                        {
                            Guid = new Guid("cec61a34-c89d-4440-9215-8d7e25ad0d32"),
                            Brand = "Seaguar",
                            Description = "Ideal for both freshwater and saltwater fishing.",
                            Diameter = 0.81999999999999995,
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 6.4299999999999997,
                            Model = "Braid X8",
                            Price = 27.32m
                        },
                        new
                        {
                            Guid = new Guid("d6d5375f-cbf5-4e89-a53d-585998d046d2"),
                            Brand = "Seaguar",
                            Description = "Lightweight and easy to handle for beginners.",
                            Diameter = 0.54000000000000004,
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 1,
                            MaxWeight = 5.5099999999999998,
                            Model = "Trilene XL",
                            Price = 44.89m
                        },
                        new
                        {
                            Guid = new Guid("d2dcc959-f019-402b-92d9-c27b5e1296b2"),
                            Brand = "Yo-Zuri",
                            Description = "Lightweight and easy to handle for beginners.",
                            Diameter = 0.22,
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-line-url.png",
                            IsDeleted = false,
                            LineType = 0,
                            MaxWeight = 7.7199999999999998,
                            Model = "InvizX",
                            Price = 40.53m
                        });
                });

            modelBuilder.Entity("FishingStore.Data.Models.Reel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReelSize")
                        .HasColumnType("int");

                    b.Property<int>("SpoolCapacity")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Reels");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("6637dbd4-7366-4c1a-8dda-bcfce185e7d3"),
                            Brand = "Penn",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 183.39m,
                            ReelSize = 5500,
                            SpoolCapacity = 200
                        },
                        new
                        {
                            Guid = new Guid("7409fe85-eab6-4a42-8b26-36d23cdc2c02"),
                            Brand = "Okuma",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 283.80m,
                            ReelSize = 5500,
                            SpoolCapacity = 380
                        },
                        new
                        {
                            Guid = new Guid("a190b100-6c1a-497d-947a-eaf7a5513af6"),
                            Brand = "Okuma",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 124.25m,
                            ReelSize = 6000,
                            SpoolCapacity = 590
                        },
                        new
                        {
                            Guid = new Guid("6df23a2f-f371-4d95-9d31-2563302cfcd3"),
                            Brand = "Lew's",
                            Description = "Lightweight design that doesn’t compromise on strength.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 498.72m,
                            ReelSize = 5000,
                            SpoolCapacity = 670
                        },
                        new
                        {
                            Guid = new Guid("2bceb323-f386-4771-8dd7-47ae520587fa"),
                            Brand = "Abu Garcia",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 569.20m,
                            ReelSize = 4000,
                            SpoolCapacity = 610
                        },
                        new
                        {
                            Guid = new Guid("b8466396-e8a6-48ee-95cb-237b157ccbc5"),
                            Brand = "Shimano",
                            Description = "High-performance reel with exceptional durability and smooth drag.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 242.99m,
                            ReelSize = 4500,
                            SpoolCapacity = 250
                        },
                        new
                        {
                            Guid = new Guid("08da4b0a-5f96-4d54-85b5-7d83eccee73c"),
                            Brand = "Abu Garcia",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 343.72m,
                            ReelSize = 5500,
                            SpoolCapacity = 790
                        },
                        new
                        {
                            Guid = new Guid("d1e9819f-d848-448b-bbdc-f7807f703c41"),
                            Brand = "Shimano",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 258.96m,
                            ReelSize = 5500,
                            SpoolCapacity = 480
                        },
                        new
                        {
                            Guid = new Guid("2da2bc28-33dd-4e0d-803e-6e3840f0ac6e"),
                            Brand = "Okuma",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 126.73m,
                            ReelSize = 4500,
                            SpoolCapacity = 670
                        },
                        new
                        {
                            Guid = new Guid("a24b31aa-7bce-4419-b3b0-958f9fa43683"),
                            Brand = "Quantum",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 212.38m,
                            ReelSize = 4500,
                            SpoolCapacity = 620
                        },
                        new
                        {
                            Guid = new Guid("ac650feb-8e76-478d-9141-895db513f9a5"),
                            Brand = "Okuma",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 200.26m,
                            ReelSize = 3000,
                            SpoolCapacity = 680
                        },
                        new
                        {
                            Guid = new Guid("08cf4a9b-2c92-4eab-9a2c-d1cd01815858"),
                            Brand = "Penn",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 479.33m,
                            ReelSize = 4500,
                            SpoolCapacity = 240
                        },
                        new
                        {
                            Guid = new Guid("ed32d3a7-93c3-4444-a553-97f4f69bd5b2"),
                            Brand = "Quantum",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tatula SV 2500",
                            Price = 304.67m,
                            ReelSize = 4000,
                            SpoolCapacity = 580
                        },
                        new
                        {
                            Guid = new Guid("6255ded0-cb81-4f9d-82ef-cefbad0a761f"),
                            Brand = "Abu Garcia",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 606.17m,
                            ReelSize = 3000,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("74bca88b-8dbd-4893-8e52-043e6c732f8f"),
                            Brand = "Quantum",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 637.60m,
                            ReelSize = 6000,
                            SpoolCapacity = 740
                        },
                        new
                        {
                            Guid = new Guid("79531d39-66dd-4749-940e-2916a7cf20a8"),
                            Brand = "Penn",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 290.33m,
                            ReelSize = 2000,
                            SpoolCapacity = 360
                        },
                        new
                        {
                            Guid = new Guid("8047f5a5-11d2-45dd-8d65-6d458409f368"),
                            Brand = "Abu Garcia",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 642.12m,
                            ReelSize = 5000,
                            SpoolCapacity = 540
                        },
                        new
                        {
                            Guid = new Guid("31aa6585-de08-421e-aba6-dcd5048fb425"),
                            Brand = "Okuma",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 304.88m,
                            ReelSize = 4000,
                            SpoolCapacity = 250
                        },
                        new
                        {
                            Guid = new Guid("b9ae97d3-95f3-4f7c-a6df-0480839e5560"),
                            Brand = "Shimano",
                            Description = "High-performance reel with exceptional durability and smooth drag.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tatula SV 2500",
                            Price = 440.94m,
                            ReelSize = 4000,
                            SpoolCapacity = 360
                        },
                        new
                        {
                            Guid = new Guid("b7032b2c-578f-46c9-be74-05eb8a306f04"),
                            Brand = "Penn",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 321.40m,
                            ReelSize = 4000,
                            SpoolCapacity = 350
                        },
                        new
                        {
                            Guid = new Guid("e404dd45-510f-4208-bd02-954b59452f28"),
                            Brand = "Shimano",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tatula SV 2500",
                            Price = 536.93m,
                            ReelSize = 3000,
                            SpoolCapacity = 790
                        },
                        new
                        {
                            Guid = new Guid("99a16972-8be0-4ecb-8ebd-cc043f3aa929"),
                            Brand = "Penn",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 278.72m,
                            ReelSize = 2000,
                            SpoolCapacity = 380
                        },
                        new
                        {
                            Guid = new Guid("02390101-6ff9-4551-b2a9-88d47fc8db6f"),
                            Brand = "Quantum",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 660.14m,
                            ReelSize = 1000,
                            SpoolCapacity = 660
                        },
                        new
                        {
                            Guid = new Guid("4437038f-b9ce-4b45-968a-9a5968f2cf3d"),
                            Brand = "Penn",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 106.66m,
                            ReelSize = 2000,
                            SpoolCapacity = 500
                        },
                        new
                        {
                            Guid = new Guid("d71d71fa-6d51-47f7-a0cc-b69d0f24f139"),
                            Brand = "Daiwa",
                            Description = "Lightweight design that doesn’t compromise on strength.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 562.23m,
                            ReelSize = 4500,
                            SpoolCapacity = 520
                        },
                        new
                        {
                            Guid = new Guid("186bbf9c-c19f-49b0-aaf6-a02e8f81b407"),
                            Brand = "Okuma",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 245.68m,
                            ReelSize = 2000,
                            SpoolCapacity = 690
                        },
                        new
                        {
                            Guid = new Guid("43ad9145-a056-4943-9803-f1424d02ff5c"),
                            Brand = "Quantum",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 593.39m,
                            ReelSize = 2000,
                            SpoolCapacity = 590
                        },
                        new
                        {
                            Guid = new Guid("89ddbcd5-9cda-4d6b-bb72-2e182bcd8345"),
                            Brand = "Lew's",
                            Description = "Versatile spinning reel for all types of fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Silver Max 3000",
                            Price = 488.87m,
                            ReelSize = 5500,
                            SpoolCapacity = 340
                        },
                        new
                        {
                            Guid = new Guid("79a66188-94b1-43c3-8b6b-82ec038a1855"),
                            Brand = "Abu Garcia",
                            Description = "Lightweight design that doesn’t compromise on strength.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 261.89m,
                            ReelSize = 4000,
                            SpoolCapacity = 370
                        },
                        new
                        {
                            Guid = new Guid("789b47a8-f58c-4161-8aad-1737962d36cc"),
                            Brand = "Lew's",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Revo X 3000",
                            Price = 665.65m,
                            ReelSize = 6000,
                            SpoolCapacity = 470
                        },
                        new
                        {
                            Guid = new Guid("ef90798b-cb0a-4f74-8106-0fc28a89f88e"),
                            Brand = "Penn",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 581.97m,
                            ReelSize = 1000,
                            SpoolCapacity = 360
                        },
                        new
                        {
                            Guid = new Guid("5da122dd-f438-4ad9-9190-ce73cf37a603"),
                            Brand = "Okuma",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 694.48m,
                            ReelSize = 5500,
                            SpoolCapacity = 670
                        },
                        new
                        {
                            Guid = new Guid("ee7b05f3-d53d-41df-8eb6-b927aaf9f6d5"),
                            Brand = "Lew's",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 539.34m,
                            ReelSize = 5500,
                            SpoolCapacity = 640
                        },
                        new
                        {
                            Guid = new Guid("907354fd-09af-4c58-8474-a0921ca1b139"),
                            Brand = "Okuma",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 165.86m,
                            ReelSize = 4000,
                            SpoolCapacity = 550
                        },
                        new
                        {
                            Guid = new Guid("f5d4d25c-04c2-4d82-ad81-b2c7b0d844ce"),
                            Brand = "Penn",
                            Description = "High-performance reel with exceptional durability and smooth drag.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 400.21m,
                            ReelSize = 4000,
                            SpoolCapacity = 550
                        },
                        new
                        {
                            Guid = new Guid("11f07013-eb8d-4c05-b91e-916504f933f1"),
                            Brand = "Abu Garcia",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 527.75m,
                            ReelSize = 4500,
                            SpoolCapacity = 610
                        },
                        new
                        {
                            Guid = new Guid("5c55f106-a011-4cb8-a770-ac4d3c20fdb5"),
                            Brand = "Okuma",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 327.73m,
                            ReelSize = 3000,
                            SpoolCapacity = 570
                        },
                        new
                        {
                            Guid = new Guid("9d96855e-4b47-4383-a479-a9dd0fba6389"),
                            Brand = "Quantum",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 236.90m,
                            ReelSize = 5500,
                            SpoolCapacity = 610
                        },
                        new
                        {
                            Guid = new Guid("ec8026ff-f538-4892-bd69-5da5f62392fc"),
                            Brand = "Shimano",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 512.87m,
                            ReelSize = 3000,
                            SpoolCapacity = 740
                        },
                        new
                        {
                            Guid = new Guid("0926a398-b265-4726-9f48-c3221d7a7e94"),
                            Brand = "Shimano",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tatula SV 2500",
                            Price = 532.40m,
                            ReelSize = 2000,
                            SpoolCapacity = 500
                        },
                        new
                        {
                            Guid = new Guid("8a7fb156-8102-46e5-b1f0-e294de7935d1"),
                            Brand = "Shimano",
                            Description = "Designed for professional anglers and enthusiasts alike.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Tournament MB 3000",
                            Price = 156.78m,
                            ReelSize = 6000,
                            SpoolCapacity = 450
                        },
                        new
                        {
                            Guid = new Guid("5e7eb6b4-4259-461f-ba2a-70202dd8121a"),
                            Brand = "Daiwa",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 172.38m,
                            ReelSize = 1000,
                            SpoolCapacity = 610
                        },
                        new
                        {
                            Guid = new Guid("4d5112b6-2dcb-4a02-bf30-7b872ddf72a3"),
                            Brand = "Shimano",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 420.45m,
                            ReelSize = 5000,
                            SpoolCapacity = 730
                        },
                        new
                        {
                            Guid = new Guid("67897b4a-6705-4c89-97a4-678b1fd678cb"),
                            Brand = "Penn",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Smoke S3 2000",
                            Price = 590.94m,
                            ReelSize = 2000,
                            SpoolCapacity = 540
                        },
                        new
                        {
                            Guid = new Guid("9a0ab941-9bb5-4723-b3d6-0524c126cd3f"),
                            Brand = "Penn",
                            Description = "Engineered for precision casting and reliability.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 131.70m,
                            ReelSize = 3000,
                            SpoolCapacity = 520
                        },
                        new
                        {
                            Guid = new Guid("f42314dd-4775-448a-9036-db5824662358"),
                            Brand = "Daiwa",
                            Description = "Great value for money with outstanding performance.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Avenger ABF6500",
                            Price = 480.26m,
                            ReelSize = 1000,
                            SpoolCapacity = 580
                        },
                        new
                        {
                            Guid = new Guid("ded6b345-0486-4223-950d-d28051458712"),
                            Brand = "Abu Garcia",
                            Description = "Features a high gear ratio for quick retrieves.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Fuego LT 2000",
                            Price = 526.67m,
                            ReelSize = 2000,
                            SpoolCapacity = 230
                        },
                        new
                        {
                            Guid = new Guid("37089196-712b-48a3-b65e-b929efa484b8"),
                            Brand = "Quantum",
                            Description = "Perfect for both freshwater and saltwater environments.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Battle II 4000",
                            Price = 238.39m,
                            ReelSize = 3500,
                            SpoolCapacity = 250
                        },
                        new
                        {
                            Guid = new Guid("d3602ebd-9df7-4ea9-9e98-729ca545f401"),
                            Brand = "Shimano",
                            Description = "Robust construction with advanced corrosion resistance.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "Vanford 2500",
                            Price = 522.04m,
                            ReelSize = 2000,
                            SpoolCapacity = 580
                        },
                        new
                        {
                            Guid = new Guid("52bde323-e3b4-45d9-9fee-4afcc66b4cc2"),
                            Brand = "Abu Garcia",
                            Description = "Equipped with smooth ball bearings for a seamless experience.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Model = "KastKing Sharky III 3000",
                            Price = 440.38m,
                            ReelSize = 3000,
                            SpoolCapacity = 410
                        });
                });

            modelBuilder.Entity("FishingStore.Data.Models.Rod", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FishingType")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Guid");

                    b.ToTable("Rods");

                    b.HasData(
                        new
                        {
                            Guid = new Guid("fdd5b471-3697-438c-926e-8bcac37aae6d"),
                            Action = 90,
                            Brand = "Okuma",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Phantom",
                            Price = 243.99m
                        },
                        new
                        {
                            Guid = new Guid("12cf7ab7-a712-4f94-b8a4-cc1bd63619c3"),
                            Action = 50,
                            Brand = "Daiwa",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Battle II",
                            Price = 466.40m
                        },
                        new
                        {
                            Guid = new Guid("236cd72f-8cdf-48a0-8fad-5d5ea78cde27"),
                            Action = 100,
                            Brand = "Daiwa",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Veritas",
                            Price = 482.23m
                        },
                        new
                        {
                            Guid = new Guid("ea785cb6-0e57-4d93-8ca5-8afa25ea89db"),
                            Action = 50,
                            Brand = "Shimano",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Veritas",
                            Price = 614.31m
                        },
                        new
                        {
                            Guid = new Guid("ba8abe3a-ea10-4905-9ad1-cdf7f721c389"),
                            Action = 100,
                            Brand = "Shimano",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Procyon",
                            Price = 162.84m
                        },
                        new
                        {
                            Guid = new Guid("d2d1be11-0379-492d-ad52-e41a520afdff"),
                            Action = 20,
                            Brand = "Shimano",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 360,
                            Model = "Tatula LT",
                            Price = 821.78m
                        },
                        new
                        {
                            Guid = new Guid("7a2f50e0-bb0e-4d3c-b001-d92909c5f097"),
                            Action = 160,
                            Brand = "Abu Garcia",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Stradic CI4+",
                            Price = 498.88m
                        },
                        new
                        {
                            Guid = new Guid("f5eebb82-163f-41d1-8dff-e477af7d2df4"),
                            Action = 180,
                            Brand = "Daiwa",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Procyon",
                            Price = 360.77m
                        },
                        new
                        {
                            Guid = new Guid("ca0a3c67-84b9-47ef-b435-13cafe8d22fd"),
                            Action = 190,
                            Brand = "Abu Garcia",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Procyon",
                            Price = 784.89m
                        },
                        new
                        {
                            Guid = new Guid("3375dc55-39fb-4704-b880-87a32161d93a"),
                            Action = 30,
                            Brand = "Shimano",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Tsunami",
                            Price = 307.60m
                        },
                        new
                        {
                            Guid = new Guid("895442da-fc82-4fd4-930c-f616e27d0472"),
                            Action = 110,
                            Brand = "Abu Garcia",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Procyon",
                            Price = 127.98m
                        },
                        new
                        {
                            Guid = new Guid("91c3fda4-8663-4b6d-b0a8-1403c31fea10"),
                            Action = 190,
                            Brand = "Okuma",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Catana",
                            Price = 94.24m
                        },
                        new
                        {
                            Guid = new Guid("90f68513-3165-43c9-9b23-dfe53daee021"),
                            Action = 80,
                            Brand = "Shimano",
                            Description = "A versatile rod perfect for carp fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Celilo",
                            Price = 701.64m
                        },
                        new
                        {
                            Guid = new Guid("cf42e07c-8ddc-45e9-af21-727c2583d171"),
                            Action = 160,
                            Brand = "Okuma",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Battle II",
                            Price = 467.29m
                        },
                        new
                        {
                            Guid = new Guid("d572150d-992a-429d-9455-12a612d44312"),
                            Action = 20,
                            Brand = "Abu Garcia",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 360,
                            Model = "Catana",
                            Price = 806.65m
                        },
                        new
                        {
                            Guid = new Guid("a2a77c70-3d31-42f1-b170-eed99d326cc2"),
                            Action = 70,
                            Brand = "Abu Garcia",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Catana",
                            Price = 164.67m
                        },
                        new
                        {
                            Guid = new Guid("67be96a2-1720-4295-84c2-41ee016719c3"),
                            Action = 140,
                            Brand = "Daiwa",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Stradic CI4+",
                            Price = 278.71m
                        },
                        new
                        {
                            Guid = new Guid("cffc73dc-24f1-467f-b966-d3ab1e71462e"),
                            Action = 120,
                            Brand = "Okuma",
                            Description = "Designed for spinning, lightweight and durable.",
                            FishingType = 1,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Celilo",
                            Price = 582.89m
                        },
                        new
                        {
                            Guid = new Guid("38adebe3-1473-477a-bbca-c7f8bea7c8ff"),
                            Action = 30,
                            Brand = "Shimano",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Phantom",
                            Price = 709.86m
                        },
                        new
                        {
                            Guid = new Guid("1ba98eb4-04f5-4fef-a79e-c9fc24ed0b61"),
                            Action = 90,
                            Brand = "Okuma",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 360,
                            Model = "Stradic CI4+",
                            Price = 772.47m
                        },
                        new
                        {
                            Guid = new Guid("2788c52b-0697-4dd8-b6dd-cb1b1b5b6390"),
                            Action = 110,
                            Brand = "Okuma",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 420,
                            Model = "Battle II",
                            Price = 853.15m
                        },
                        new
                        {
                            Guid = new Guid("9d54e4e7-e921-4e47-ace6-d331f6797fd8"),
                            Action = 70,
                            Brand = "Abu Garcia",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 3,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 330,
                            Model = "Celilo",
                            Price = 163.34m
                        },
                        new
                        {
                            Guid = new Guid("7fd83d7b-eadb-4b29-9676-e2e3bce28436"),
                            Action = 190,
                            Brand = "Penn",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 2,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 300,
                            Model = "Tsunami",
                            Price = 354.63m
                        },
                        new
                        {
                            Guid = new Guid("cb98f198-7ab6-4e23-b8ba-ea7fec0dfb92"),
                            Action = 60,
                            Brand = "Daiwa",
                            Description = "Excellent for float fishing with enhanced accuracy.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 450,
                            Model = "Battle II",
                            Price = 801.87m
                        },
                        new
                        {
                            Guid = new Guid("9e6b3c64-bec3-46a4-b065-9dc3e3184e7f"),
                            Action = 90,
                            Brand = "Shimano",
                            Description = "Great sensitivity for feeder fishing.",
                            FishingType = 0,
                            ImageUrl = "~/img/no-img-rod-url.jpg",
                            IsDeleted = false,
                            Length = 390,
                            Model = "Tatula LT",
                            Price = 180.98m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FishingStore.Data.Models.FullSet", b =>
                {
                    b.HasOne("FishingStore.Data.Models.Hook", "Hook")
                        .WithMany()
                        .HasForeignKey("HookGuid");

                    b.HasOne("FishingStore.Data.Models.Line", "Line")
                        .WithMany()
                        .HasForeignKey("LineGuid");

                    b.HasOne("FishingStore.Data.Models.Reel", "Reel")
                        .WithMany()
                        .HasForeignKey("ReelGuid");

                    b.HasOne("FishingStore.Data.Models.Rod", "Rod")
                        .WithMany()
                        .HasForeignKey("RodGuid");

                    b.HasOne("FishingStore.Data.Models.ApplicationUser", "ApplicationUser")
                        .WithMany("FullSets")
                        .HasForeignKey("UserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Hook");

                    b.Navigation("Line");

                    b.Navigation("Reel");

                    b.Navigation("Rod");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("FishingStore.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FishingStore.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("FullSets");
                });
#pragma warning restore 612, 618
        }
    }
}
